version: '3'
services:
  frontend:
    build: ./client
    ports:
      - "3000:3000"
  backend:
    build: ./backend
    ports:
      - "3001:3000"
    links:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
